#!/bin/bash

echo "---------------- installing mongodb"
sudo cp installation-materials/mongodb-org-8.0.repo /etc/yum.repos.d/ || exit 1
sudo yum install -y mongodb-org || exit 1

echo "---------------- starting mongod as a systemd service"
sudo systemctl start mongod || exit 1
sudo systemctl status mongod || exit 1
sudo systemctl enable mongod || exit 1 // restart after reboot

echo "---------------- installing nodejs"
curl -sL https://rpm.nodesource.com/setup_23.x | sudo bash - || exit 1
sudo yum install -y nodejs || exit 1
node --version || exit 1

echo "---------------- allowing node to receive network connections"
sudo /usr/sbin/setcap 'cap_net_bind_service=+ep' /usr/bin/node || exit 1

echo "---------------- installing the AWS SDK for JavaScript"
npm install @aws-sdk/client-ses || exit 1

echo "---------------- installing dependencies"
npm install . || exit 1

echo "---------------- prompting for the hostname in the email verification link"
read -p "please enter the public ip address of this EC2 instance, or a domain name mapping to the address: " host
sed -i s/HOSTNAME/$host/g demo.mjs || exit 1

echo "---------------- asking whether to use real email (see README.md)"
read -p "enter yes to use real email, anything else to use simulated email: " realemail
if [ "$realemail" != "yes" ]
then
    sed -i s/REALEMAIL/SIMULATED/g demo.mjs || exit 1
    echo "Email will be simulated"
else
    echo "---------------- prompting for the sender address in the email verification link"
    read -p "please enter a verified address to be used as the sender address in the email verification message: " senderaddress
    sed -i s/SENDERADDRESS/$senderaddress/g demo.mjs || exit 1
fi

echo "---------------- installing the demo as a systemd service"
sudo cp installation-materials/demo.service /etc/systemd/system || exit 1

echo "---------------- starting the demo"
sudo systemctl start demo || exit 1
sudo systemctl status demo || exit 1

echo "---------------- success"
echo "demo started successfully;"
echo "to stop it:"
echo "    sudo systemctl stop demo"
echo "to restart it from bash:"
echo "    node /home/ec2-user/crypto-authn-demo-nosql/demo.mjs"
echo "to restart it as a systemd service:"
echo "    sudo systemctl start demo"
echo "to restart it automatically on reboot:"
echo "    sudo systemctl enable demo"
echo " "
echo "INSTALLATION SUCCESSFUL" 
echo " "
